# Generated by Django 6.0.6 on 2026-07-22 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.category'),
        ),
    ]
