# Generated by Django 6.0.6 on 2026-07-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
