# Generated by Django 6.0.6 on 2026-08-06 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0007_leave_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
