# Generated by Django 6.0.6 on 2026-08-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0008_leave_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(default='Casual Leave', max_length=100),
        ),
    ]
